# Generated by Django 4.2.5 on 2023-09-23 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karbaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tutorial name')),
                ('price', models.IntegerField(verbose_name='Tutorial price')),
                ('description', models.CharField(max_length=300, verbose_name='Tutorial description')),
                ('is_active', models.BooleanField(verbose_name='active/notactive')),
                ('ratings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='rating product')),
                ('slug', models.SlugField(default='', verbose_name='title in url')),
            ],
        ),
    ]
