# Generated by Django 4.2.5 on 2023-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_productcategory_delete_karbaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=400, unique=True, verbose_name='title in url'),
        ),
    ]
